name: Test Runner
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']

    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test
